# Email Spam Classifier

In [59]:
import pandas as pd
import numpy as np
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score
from sklearn.metrics import confusion_matrix 

In [61]:
df = pd.read_csv("emails.csv")
df.head()
result = {}

In [39]:
X = df.drop(columns=['Email No.','Prediction'])
y = df['Prediction']
X

the  to  ect  and  for  of    a  you  hou  in  ...  enhancements  \
0       0   0    1    0    0   0    2    0    0   0  ...             0   
1       8  13   24    6    6   2  102    1   27  18  ...             0   
2       0   0    1    0    0   0    8    0    0   4  ...             0   
3       0   5   22    0    5   1   51    2   10   1  ...             0   
4       7   6   17    1    5   2   57    0    9   3  ...             0   
...   ...  ..  ...  ...  ...  ..  ...  ...  ...  ..  ...           ...   
5167    2   2    2    3    0   0   32    0    0   5  ...             0   
5168   35  27   11    2    6   5  151    4    3  23  ...             0   
5169    0   0    1    1    0   0   11    0    0   1  ...             0   
5170    2   7    1    0    2   1   28    2    0   8  ...             0   
5171   22  24    5    1    6   5  148    8    2  23  ...             0   

      connevey  jay  valued  lay  infrastructure  military  allowing  ff  dry  
0            0    0       0    0               0         0         0   0    0  
1            0    0       0    0               0         0         0   1    0  
2            0    0       0    0               0         0         0   0    0  
3            0    0       0    0               0         0         0   0    0  
4            0    0       0    0               0         0         0   1    0  
...        ...  ...     ...  ...             ...       ...       ...  ..  ...  
5167         0    0       0    0               0         0         0   0    0  
5168         0    0       0    0               0         0         0   1    0  
5169         0    0       0    0               0         0         0   0    0  
5170         0    0       0    0               0         0         0   1    0  
5171         0    0       0    0               0         0         0   0    0  

[5172 rows x 3000 columns]

In [40]:
# split into training and testing sets
# USE from sklearn.model_selection import train_test_split to avoid seeing deprecation warning.
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(X, 
                                                    y, 
                                                    test_size =0.2, 
                                                    random_state=1)


print('Number of rows in the total set: {}'.format(df.shape[0]))
print('Number of rows in the training set: {}'.format(X_train.shape[0]))
print('Number of rows in the test set: {}'.format(X_test.shape[0]))

Number of rows in the total set: 5172
Number of rows in the training set: 4137
Number of rows in the test set: 1035


# Using Logistic Regression

In [56]:
#Train the data
clf = LogisticRegression(random_state=0).fit(X_train, y_train)
#predict the value
predictions = clf.predict(X_test)
predictions

/home/admin1/anaconda3/lib/python3.9/site-packages/sklearn/linear_model/_logistic.py:458: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


array([0, 1, 0, ..., 0, 0, 0])

In [62]:

result["Logistic Regression"] = {"Accuracy score": accuracy_score(y_test, predictions), "Precision Score": precision_score(y_test, predictions), "Recall Score": recall_score(y_test, predictions), "F1 score":f1_score(y_test, predictions)}

In [63]:
print('Accuracy score: ', format(accuracy_score(y_test, predictions)))
print('Precision score: ', format(precision_score(y_test, predictions)))
print('Recall score: ', format(recall_score(y_test, predictions)))
print('F1 score: ', format(f1_score(y_test, predictions)))
print('\nConfusion Matrix :\n', confusion_matrix(y_test, predictions)) 

Accuracy score:  0.9584541062801932
Precision score:  0.9278996865203761
Recall score:  0.9367088607594937
F1 score:  0.9322834645669291

Confusion Matrix :
 [[696  23]
 [ 20 296]]


# Usign Naive Bayes

In [64]:
from sklearn.naive_bayes import MultinomialNB
naive_bayes = MultinomialNB()
naive_bayes.fit(X_train,y_train)
predictions = naive_bayes.predict(X_test)

In [65]:

result["Maive Bayes"] = {"Accuracy score": accuracy_score(y_test, predictions), "Precision Score": precision_score(y_test, predictions), "Recall Score": recall_score(y_test, predictions), "F1 score":f1_score(y_test, predictions)}

In [66]:

print('Accuracy score: {}'.format(accuracy_score(y_test, predictions)))
print('Precision score: {}'.format(precision_score(y_test, predictions)))
print('Recall score: {}'.format(recall_score(y_test, predictions)))
print('F1 score: {}'.format(f1_score(y_test, predictions)))

Accuracy score: 0.9420289855072463
Precision score: 0.869942196531792
Recall score: 0.9525316455696202
F1 score: 0.9093655589123867


# Using SVM

In [67]:
from sklearn import svm
#SVM with linear kernel
clf=svm.SVC(kernel='linear')
clf.fit(X_train,y_train)
predictions=clf.predict(X_test)
predictions

array([0, 1, 0, ..., 0, 0, 0])

In [68]:

result["SVM"] = {"Accuracy score": accuracy_score(y_test, predictions), "Precision Score": precision_score(y_test, predictions), "Recall Score": recall_score(y_test, predictions), "F1 score":f1_score(y_test, predictions)}

In [69]:

print('Accuracy score: {}'.format(accuracy_score(y_test, predictions)))
print('Precision score: {}'.format(precision_score(y_test, predictions)))
print('Recall score: {}'.format(recall_score(y_test, predictions)))
print('F1 score: {}'.format(f1_score(y_test, predictions)))

Accuracy score: 0.9507246376811594
Precision score: 0.917981072555205
Recall score: 0.9208860759493671
F1 score: 0.9194312796208529


# Using KNN

In [70]:
from sklearn.neighbors import KNeighborsClassifier
knn = KNeighborsClassifier(n_neighbors=7)
knn.fit(X_train, y_train)
predictions = knn.predict(X_test)
predictions

array([0, 1, 0, ..., 0, 0, 0])

In [71]:

result["KNN"] = {"Accuracy score": accuracy_score(y_test, predictions), "Precision Score": precision_score(y_test, predictions), "Recall Score": recall_score(y_test, predictions), "F1 score":f1_score(y_test, predictions)}

In [72]:
print('Accuracy score: {}'.format(accuracy_score(y_test, predictions)))
print('Precision score: {}'.format(precision_score(y_test, predictions)))
print('Recall score: {}'.format(recall_score(y_test, predictions)))
print('F1 score: {}'.format(f1_score(y_test, predictions)))

Accuracy score: 0.8714975845410629
Precision score: 0.7606837606837606
Recall score: 0.8449367088607594
F1 score: 0.800599700149925


# Using Random Forest

In [73]:
from sklearn.ensemble import RandomForestClassifier
clf = RandomForestClassifier(max_depth=2, random_state=0)
clf.fit(X_train, y_train)
predictions = clf.predict(X_test)
predictions

array([0, 0, 0, ..., 0, 0, 0])

In [74]:

result["Random Forest"] = {"Accuracy score": accuracy_score(y_test, predictions), "Precision Score": precision_score(y_test, predictions), "Recall Score": recall_score(y_test, predictions), "F1 score":f1_score(y_test, predictions)}

In [75]:
print('Accuracy score: {}'.format(accuracy_score(y_test, predictions)))
print('Precision score: {}'.format(precision_score(y_test, predictions)))
print('Recall score: {}'.format(recall_score(y_test, predictions)))
print('F1 score: {}'.format(f1_score(y_test, predictions)))

Accuracy score: 0.7130434782608696
Precision score: 1.0
Recall score: 0.060126582278481014
F1 score: 0.11343283582089551


# Using Decision Tree

In [76]:
from sklearn.tree import DecisionTreeClassifier
clf = DecisionTreeClassifier(random_state=0)
clf.fit(X_train, y_train)
predictions = clf.predict(X_test)
predictions

array([0, 1, 0, ..., 0, 0, 0])

In [77]:

result["Decision Tree"] = {"Accuracy score": accuracy_score(y_test, predictions), "Precision Score": precision_score(y_test, predictions), "Recall Score": recall_score(y_test, predictions), "F1 score":f1_score(y_test, predictions)}

In [78]:
print('Accuracy score: {}'.format(accuracy_score(y_test, predictions)))
print('Precision score: {}'.format(precision_score(y_test, predictions)))
print('Recall score: {}'.format(recall_score(y_test, predictions)))
print('F1 score: {}'.format(f1_score(y_test, predictions)))

Accuracy score: 0.9391304347826087
Precision score: 0.8940809968847352
Recall score: 0.9082278481012658
F1 score: 0.901098901098901


In [80]:
r_df = pd.DataFrame(result)
r_df

Logistic Regression  Maive Bayes       SVM       KNN  \
Accuracy score              0.958454     0.942029  0.950725  0.871498   
Precision Score             0.927900     0.869942  0.917981  0.760684   
Recall Score                0.936709     0.952532  0.920886  0.844937   
F1 score                    0.932283     0.909366  0.919431  0.800600   

                 Random Forest  Decision Tree  
Accuracy score        0.713043       0.939130  
Precision Score       1.000000       0.894081  
Recall Score          0.060127       0.908228  
F1 score              0.113433       0.901099